# Join our discord - https://discord.gg/YGzA4UxzFB you can find another good plugins there.
# Permissions
# "ultraLeafDecay.reload" - permission required to use "/ultraleafdecay reload" command

# Maximum distance from leaves to the nearest log block
# Leaves with distance greater than or equal to this value will be destroyed
# Default: 6 (matches vanilla Minecraft behavior)
# Range: 1-7 (values outside this range may cause unexpected behavior)
maxLogDistance: 6

# supports MiniMessage
noPermissionToReload: "<red>✘ <white>You don't have permission to reload Config!"
configReloaded: "<green>✔ <white>Config reloaded!"